
--USER INFO
CREATE TABLE USER(
uId INT(11) NOT NULL AUTO_INCREMENT,
userName VARCHAR(20),
password VARCHAR(20),
CONSTRAINT uId_pk PRIMARY KEY(uId)
);

CREATE TABLE CLIENT(
uId INT(11) DEFAULT NULL,
fName VARCHAR(20),
lName VARCHAR(20),
emailAddress VARCHAR(40),
street VARCHAR(50),
city VARCHAR(20),
zip INT,
CONSTRAINT uId_fk FOREIGN KEY(uId) REFERENCES USER(uId)
);

--ORDER
CREATE TABLE ORDERS(
uId INT(11),
orId INT(11) NOT NULL AUTO_INCREMENT,
oDate DATE,
payId INT,
PRIMARY KEY(orId),
FOREIGN KEY(uId) REFERENCES USER (uId)
);

CREATE TABLE ORDERDETAILS(
orId INT(11),
orIdDetails INT(11) NOT NULL AUTO_INCREMENT,
pId INT,
pPrice INT,
tTotal INT,
pQuantity INT,
PRIMARY KEY(orIdDetails),
FOREIGN KEY(pId) REFERENCES PRODUCTS (pId),
CONSTRAINT FOREIGN KEY(orId) REFERENCES ORDERS (orId)
);

--PRODUCTS
CREATE TABLE PRODUCTS(
pId INT(11) NOT NULL AUTO_INCREMENT,
pName VARCHAR(20),
pDescription VARCHAR(100),
pPrice INT,
pPicture INT,
pQuantity INT,
catId INT,
PRIMARY KEY(pId),
FOREIGN KEY(catId) REFERENCES CATEGORY (catId)
);

CREATE TABLE CATEGORY(
catId INT NOT NULL AUTO_INCREMENT,
catType VARCHAR(20),
PRIMARY KEY (catId)
);

--SHOPPING
CREATE TABLE SHOPPINGCART(
cartId INT NOT NULL AUTO_INCREMENT,     
orId INT,
PRIMARY KEY(cartId),
FOREIGN KEY(orId) REFERENCES ORDERS (orId)
);

